### ISSUE TITLE
Improve messaging when errors occur retrieving values from container

### ISSUE THREAD

**Issue by Firehed** [Firehed/container#20]
At present, if an exception is thrown when retrieving data from the container, a nearly-useless stack trace is generated. This is especially cryptic for the compiled container, typically used in production environments.

Example:
```
ErrorException: Undefined array key "host" in /var/www/html/.generated/config.php:1831
Stack trace:
#0 /var/www/html/.generated/config.php(1831): {closure}(2, 'Undefined array...', '/var/www/html/....', 1831)
#1 /var/www/html/.generated/config.php(1835): CC_6dde1f79459579519fe1e4b8059ec86c->{closure}(Object(CC_6dde1f79459579519fe1e4b8059ec86c))
#2 /var/www/html/vendor/firehed/container/src/CompiledContainer.php(54): CC_6dde1f79459579519fe1e4b8059ec86c->get7a4806bdfecf888d79f1c5c7c069e8fb()
#3 /var/www/html/.generated/config.php(1820): Firehed\Container\CompiledContainer->get('production_post...')
#4 /var/www/html/.generated/config.php(1821): CC_6dde1f79459579519fe1e4b8059ec86c->{closure}(Object(CC_6dde1f79459579519fe1e4b8059ec86c))
#5 /var/www/html/vendor/firehed/container/src/CompiledContainer.php(54): CC_6dde1f79459579519fe1e4b8059ec86c->getb73dd889c3da9ab8760efabdea8c8919()
# ...
```

Ideally, something functionally equivalent to a javascript sourcemap would allow the raw config source files to get tied into the error message, when one occurs. However that may not be possible at runtime, and may be excessively complex to integrate into the build process. As a simple starting point, catching, wrapping, and re-throwing an exception at runtime that makes the `id` of the value being retrieved clearer would be beneficial. Per the PSR guidelines, the wrapper exception should be an instanceof `ContainerExceptionInterface`.

**Comment by Firehed** [comment]
Additionally, when using the `DevContainer`, a similarly unhelpful message is generated:

```
Uncaught exception: Firehed\Container\Exceptions\NotFound: parser
```

in this case, `parser` is the _name_ of the parameter that's supposed to be injected, not its type.
